apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ template "cp-ksql-server.fullname" . }}
  labels:
    app: {{ template "cp-ksql-server.name" . }}
    chart: {{ template "cp-ksql-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: ksql-server
      port: {{ .Values.servicePort }}
    {{ if .Values.jmx.port }}
    - name: jmx
      port: {{ .Values.jmx.port }}
   {{ end }}
  selector:
    app: {{ template "cp-ksql-server.name" . }}
    release: {{ .Release.Name }}
