apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "cp-kafka-connect.fullname" . }}
  labels:
    app: {{ template "cp-kafka-connect.name" . }}
    chart: {{ template "cp-kafka-connect.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if or .Values.podAnnotations }}
    annotations:
      {{- range $key, $value := .Values.ingressAnnotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
  name: kafka-connect
  namespace: confluent-kafka
  labels:
    app: kafka-connect
  annotations:
    # https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guapie/nginx-configuration/annotations.md
    kubernetes.io/ingress.class: "nginx"
    external-dns.alpha.kubernetes.io/hostname: "kafka-connect.dev.terradatum.com."
    external-dns.alpha.kubernetes.io/ttl: "300"
spec:
  ingressClassName: "nginx"
  rules:
    - host: "kafka-connect.dev.terradatum.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kafka-connect
                port:
                  number: 80
