apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ template "cp-kafka-rest.fullname" . }}
  labels:
    app: {{ template "cp-kafka-rest.name" . }}
    chart: {{ template "cp-kafka-rest.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - name: kafka-rest
      port: {{ .Values.servicePort }}
    {{- if .Values.jmx.port }}
    - name: jmx
      port: {{ .Values.jmx.port }}
    {{- end }}
  selector:
    app: {{ template "cp-kafka-rest.name" . }}
    release: {{ .Release.Name }}
